mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    #- hyde.ext.plugins.meta.SorterPlugin
    #- hyde.ext.plugins.meta.GrouperPlugin
    #- hyde.ext.plugins.meta.TaggerPlugin
context:
    data:
        site_title: Nick Foti
        author:
            name: Nick Foti
            url: "http://nfoti.github.io"
            email: "firstinitiallastname at uw dot edu"
            office: "B-316 Padelford Hall"
        #google_analytics_id: UA-XXXXX-YY
        home_url: index.html
        navbar:
            - title: About
              url: index.html
            - title: Publications
              url: publications.html
            - title: Blog
              url: "http://cs.dartmouth.edu/~nfoti/blog"
        menu:
            - title: Home
              url: index.html
            - title: Landing
              url: landing.html

